version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: agrep_container
    restart: on-failure
    environment:
      POSTGRES_USER: agrep
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: agrepDB
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

volumes:
  db-data: